# Generated by Django 6.0.7 on 2026-08-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_leetcodetopic_leetcodequestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('target_problems', models.PositiveIntegerField(default=0)),
                ('completed_problems', models.PositiveIntegerField(default=0)),
                ('target_minutes', models.PositiveIntegerField(default=0)),
                ('completed_minutes', models.PositiveIntegerField(default=0)),
                ('focus_topics', models.JSONField(blank=True, default=list)),
                ('focus_difficulties', models.JSONField(blank=True, default=list)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.DeleteModel(
            name='LeetCodeQuestion',
        ),
        migrations.DeleteModel(
            name='LeetCodeTopic',
        ),
        migrations.AddIndex(
            model_name='weeklystudyplan',
            index=models.Index(fields=['user', 'status'], name='recommendat_user_id_73371f_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklystudyplan',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='unique_user_weekly_study_plan'),
        ),
    ]
