# Generated by Django 6.0.7 on 2026-08-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('submitted_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leetcode.leetcodeprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
