# Generated by Django 6.0.7 on 2026-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0002_leetcodesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodesubmission',
            name='difficulty',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
