# Generated by Django 6.0.7 on 2026-08-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0003_leetcodesubmission_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('difficulty', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LeetCodeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leetcodesubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='leetcode.leetcodequestion'),
        ),
        migrations.AddField(
            model_name='leetcodequestion',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='leetcode.leetcodetopic'),
        ),
    ]
